name: Print Hello World

on:
    push:
      branches:
        - main
    pull_request:
        types:
            - labeled
            - synchronize

jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - run: npm ci
            - run: npm test
            - name: "Say Hello"
              uses: ./.github/actions/print
              with:
                who-to-greet: Maxime

    sayBye:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout du code
              uses: actions/checkout@v4

            - name: "Say Bye"
              run: echo "Goodbye"
            